### ISSUE TITLE
Bug: Oauth sessions need to be cleared

### ISSUE THREAD

**Issue by PokeJofeJr4th** [rit-sse/WebsiteTheSSEquel#159]
Many of us are having issues with OAuth. The login screen returns various errors.

These errors can temporarily be fixed by removing your row in the user and session tables and deleting your cookies in the browser.

We believe this is due to next auth failing to renew old sessions or the seed data that's not connected to actual users. With our current setup, we need this data to run postman tests. We should try to find a way to test the auth without using this seed data.

**Comment by PokeJofeJr4th** [comment]
![image_720](https://github.com/user-attachments/assets/4081eb89-71ba-421f-8f74-cc121117bf7a)

**Comment by rtyocum** [comment]
Issue Caused by Next-Auth version bump. Older versions used this in the Account database
![image](https://github.com/user-attachments/assets/94e8315f-7f63-4c14-90e2-2d8bba93e239)

Next-Auth does not allow 2 providers of the same email address. Next-Auth updated provider from google.com to google. The image above breaks oAuth.

![image](https://github.com/user-attachments/assets/a535a586-2f02-416d-8d25-6211b90210a3)
This is the current version of the Google Auth in next-auth: https://github.com/nextauthjs/next-auth/blob/e67a1eb961f232eb55a8ef7cf6be783b97bd4187/packages/next-auth/src/providers/google.ts


Seed data should be updated to match

**Comment by Anty120** [comment]
The above might work, but if it doesn't, you may also need to delete everything in the sessions table so that the sessions table is empty. Then try to run the app again, and it oauth should work now.
